# This config may be overridden by creating a gulp-config--custom.yml file
css:
  enabled: true
  src:
    - source/sass/**/*.scss
  vendor:
    - source/css/vendor/**/*.css
  dest: public/css/
  flattenDestOutput: true
  lint:
    enabled: false
    failOnError: false
    # Add to the main src glob - useful for exclusions with `!`
    extraSrc:
#      - '!excluded-file.scss'
  # enables additional debugging information in the output file as CSS comments - only use when necessary
  sourceComments: false
  sourceMapEmbed: false
  # tell the compiler whether you want 'expanded' or 'compressed' output code
  outputStyle: compressed
  autoPrefixerBrowsers: # https://github.com/ai/browserslist#queries
    - last 2 versions
    - IE >= 9
  includePaths:
    - ./node_modules

js:
  enabled: true
  src:
    - source/js/vendor/**/*.js
    - source/js/**/*.js
    - '!source/js/example.js'
  dest: public/js/
  destName: scripts.js
  sourceMapEmbed: false
  uglify: true
  preserveLicense: false
  eslint:
    enabled: false
    # Add to the main src glob - useful for exclusions with `!`
    extraSrc:
      - '!js/vendor/**/*.js'
#      - gulpfile.js
#      - gulp_tasks/**/*.js

bowerFiles:
  enabled: true
  dir: bower_components
  includePaths:
    - bower_components/singularity/stylesheets
    - bower_components/breakpoint-sass/stylesheets
    - bower_components/sass-toolkit/stylesheets
    - bower_components/support-for/sass
    - bower_components/normalize.scss/sass

browserSync:
  enabled: true
  port: 3050
  watchFiles:
#    - '**/*.html'
#  domain: mydomain.local
  baseDir: ./
  startPath: 'public'
  openBrowserAtStart: true
  # requires above to be true; allows non-default browser to open
  browser:
    - Google Chrome
  # Tunnel the Browsersync server through a random Public URL
  # -> http://randomstring23232.localtunnel.me
  tunnel: false
  reloadDelay: 50
  reloadDebounce: 750

images:
  src: source/images/
  dest: public/images/
